### ISSUE TITLE
JWPlayer

### ISSUE THREAD

**Issue by p1r473** [ftpmorph/ftpihole#2]
Hello,
Currently, you are blocking JWPlayer that breaks embedded videos in smartphone-ads-tracking.txt 
Example: embedded video on https://www.investopedia.com/terms/s/stop-limitorder.asp
Domains that need unblocking:
cdn.jwplayer.com
ssl.p.jwpcdn.com
content.jwplatform.com
These domains are not spying or ad-related or malicious. They are just required for the playing of the JWPlayer content.

**Comment by ftpmorph** [comment]
I have commented out the domains you listed. Updating the list will remove the blocks.

They were added because JWPlayer is also used to serve ads. But since it also serves up legitimate content I have removed the blocks on those domains.

**Comment by p1r473** [comment]
Thanks!
